name: 'Setup Conan'
description: 'Install Conan package manager'
inputs:
  profile:
    description: 'Used profile'
    required: true
  shell:
    description: 'Used shell for executing commands'
    required: false
    default: ${{ runner.os == 'Linux' && 'bash' || 'pwsh' }}

runs:
  using: 'composite'
  steps:
    - name: Install Conan
      shell: ${{ inputs.shell }}
      run: pipx install conan
    - name: Echo installed version
      shell: ${{ inputs.shell }}
      run: |
        conan --version
        echo "version=$(conan --version)" >> $GITHUB_OUTPUT

    - name: Install Conan configuration files
      shell: ${{ inputs.shell }}
      run: |
        conan config install conan/global.conf

    - name: Set environment variables
      if: ${{ runner.os == 'Linux' }}
      shell: ${{ inputs.shell }}
      run: |
          echo "CONAN_CACHE_LOCATION=$(conan config home)" >> $GITHUB_ENV

    - name: Set environment variables
      if: ${{ runner.os == 'Windows' }}
      shell: ${{ inputs.shell }}
      run: |
        echo "CONAN_CACHE_LOCATION=$(conan config home)" >> $env:GITHUB_ENV

    - name: Cache Conan packages
      id: cache-conan-packages
      uses: actions/cache@v4
      with:
        path: ${{ env.CONAN_CACHE_LOCATION }}/p
        key: ${{ inputs.profile }}-${{ hashFiles('conanfile.py') }}
        
    - name: Detect default profile
      shell: ${{ inputs.shell }}
      run: |
        conan profile detect --force

    - name: Checkout private recipes repository
      uses: actions/checkout@v4
      with:
        repository: jan-kelemen/conan-recipes
        path: recipes

    - name: Override public Conan recipes
      shell: ${{ inputs.shell }}
      run: |
        conan export recipes/recipes/freetype/meson --version 2.13.3
        conan export recipes/recipes/fastgltf/all --version 0.8.0
        conan export recipes/recipes/imgui/all --version 1.91.6-docking
        conan export recipes/recipes/joltphysics/all --version 5.2.0
        conan export recipes/recipes/meshoptimizer/all --version 0.22
        conan export recipes/recipes/sdl/all --version 2.30.11
        conan export recipes/recipes/simdjson/all --version 3.11.5
        conan export recipes/recipes/spdlog/all --version 1.15.x
        conan export recipes/recipes/spirv-headers/all --version 1.4.304.0
        conan export recipes/recipes/spirv-cross/all --version 1.4.304.0
        conan export recipes/recipes/spirv-tools/all --version 1.4.304.0
        conan export recipes/recipes/glslang/all --version 1.4.304.0
        conan export recipes/recipes/volk/all --version 1.4.304.0
        conan export recipes/recipes/vulkan-headers/all --version 1.4.304.0
        conan export recipes/recipes/vulkan-memory-allocator/all --version 3.2.0

    - name: Build all dependencies
      shell: ${{ inputs.shell }}
      run: |
        conan install . --build=missing --profile=ci/conan/${{ inputs.profile }}

    - name: Cleanup temporary folders from cache
      shell: ${{ inputs.shell }}
      run: |
        conan cache clean --temp --source
