name: 'Install Vulkan SDK'
description: 'Install Vulkan SDK'
inputs:
  version:
    description: 'Version to install'
    required: false
    default: '1.4.321.1'
runs:
  using: 'composite'
  steps:
    - name: Cache Vulkan SDK
      id: cache-vulkan-sdk
      uses: actions/cache@v4
      with:
        path: "C:\\VulkanSDK\\${{ inputs.version }}"
        key: vulkan-sdk-${{ inputs.version }}

    - name: Setup Vulkan
      if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ inputs.version }}/windows/vulkansdk-windows-X64-${{ inputs.version }}.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("--accept-licenses --default-answer --confirm-command install");
          $installer.WaitForExit();

    - name: Set PATH variable
      shell: pwsh
      run: |
        "C:\VulkanSDK\${{ inputs.version }}\Bin" >> $env:GITHUB_PATH

