name: 'Upload Conan packages'
description: 'Upload built Conan packages'

runs:
  using: 'composite'
  steps:
    - name: Install Conan configuration files
      shell: bash
      run: |
        conan upload --confirm -r niku-remote "*"

