name: Weekly Debug Builds

on:
  schedule:
    - cron: '30 18 * * 0'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-24.04
    environment: Conan
    
    env:
      GCC_VER: 14
      CLANG_VER: 21
      
    strategy:
      fail-fast: false
      matrix:
        profile: [gcc-amd64-linux, clang-libstdcxx-amd64-linux, clang-libcxx-amd64-linux]
        
    steps:
      - name: Checkout repository from github
        uses: actions/checkout@v6

      - name: Install gcc-${{ env.GCC_VER }}
        uses: ./.github/actions/install-gcc
        with:
          version: ${{ env.GCC_VER }}

      - name: Install clang-${{ env.CLANG_VER }}
        if: contains(matrix.profile, 'clang')
        uses: ./.github/actions/install-clang 
        with:
          version: ${{ env.CLANG_VER }}

      - name: Install APT packages
        uses: ./.github/actions/install-apt-packages

      - name: Setup Conan
        id: setup-conan
        uses: ./.github/actions/setup-conan
        with:
          profile: ${{ matrix.profile }}
          url: ${{ secrets.CONAN_REMOTE_URL }}
          token: ${{ secrets.CONAN_REMOTE_TOKEN }}
          username: ${{ secrets.CONAN_REMOTE_USERNAME }}

      - name: Configure CMake
        run: |
          cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DNIKU_REGISTER_GPU_UNIT_TESTS=OFF --preset debug

      - name: Build
        run: |
          cmake --build --parallel --preset debug
      
      - name: Test
        run: |
          ctest --preset debug

  windows-msvc:
    runs-on: windows-2025
    environment: Conan
    
    strategy:
      fail-fast: false
      matrix:
        profile: [msvc-amd64-windows]
        
    steps:
      - name: Initialize
        run: |
          git config --global core.autocrlf input
          
      - name: Checkout repository from github
        uses: actions/checkout@v6

      - name: Install Chocolatey packages
        run: |
          choco install cmake --version 4.2.3 -y

      - name: Setup Conan
        id: setup-conan
        uses: ./.github/actions/setup-conan
        with:
          profile: ${{ matrix.profile }}
          url: ${{ secrets.CONAN_REMOTE_URL }}
          token: ${{ secrets.CONAN_REMOTE_TOKEN }}
          username: ${{ secrets.CONAN_REMOTE_USERNAME }}

      - name: Configure CMake
        run: |
          cmake -DNIKU_REGISTER_GPU_UNIT_TESTS=OFF --preset default
          
      - name: Build
        run: |
          cmake --build --parallel --preset multi-debug

      - name: Test
        run: |
          ctest --preset multi-debug

  windows-msvc-2026:
    runs-on: windows-2025-vs2026
    environment: Conan
    
    strategy:
      fail-fast: false
      matrix:
        profile: [msvc-2026-amd64-windows]
        
    steps:
      - name: Initialize
        run: |
          git config --global core.autocrlf input
          
      - name: Checkout repository from github
        uses: actions/checkout@v6

      - name: Install Chocolatey packages
        run: |
          choco install cmake --version 4.2.3 -y

      - name: Setup Conan
        id: setup-conan
        uses: ./.github/actions/setup-conan
        with:
          profile: ${{ matrix.profile }}
          url: ${{ secrets.CONAN_REMOTE_URL }}
          token: ${{ secrets.CONAN_REMOTE_TOKEN }}
          username: ${{ secrets.CONAN_REMOTE_USERNAME }}

      - name: Configure CMake
        run: |
          cmake -DNIKU_REGISTER_GPU_UNIT_TESTS=OFF --preset default
          
      - name: Build
        run: |
          cmake --build --parallel --preset multi-debug

      - name: Test
        run: |
          ctest --preset multi-debug

  windows-clang:
    runs-on: windows-2025
    environment: Conan
    
    env:
      CLANG_VER: 21
      
    strategy:
      fail-fast: false
      matrix:
        profile: [clang-amd64-windows]

    steps:
      - name: Initialize
        run: |
          git config --global core.autocrlf input
          
      - name: Checkout repository from github
        uses: actions/checkout@v6

      - name: Install Chocolatey packages
        run: |
          choco install cmake --version 4.2.3 -y
          choco install ninja
          choco install llvm --version 21.1.7 -y
          
      - name: Setup Conan
        id: setup-conan
        uses: ./.github/actions/setup-conan
        with:
          profile: ${{ matrix.profile }}
          url: ${{ secrets.CONAN_REMOTE_URL }}
          token: ${{ secrets.CONAN_REMOTE_TOKEN }}
          username: ${{ secrets.CONAN_REMOTE_USERNAME }}

      - name: Configure CMake
        run: |
          cmake -G=Ninja -DCMAKE_INSTALL_PREFIX=${{ matrix.profile }} -DNIKU_REGISTER_GPU_UNIT_TESTS=OFF --preset debug
          
      - name: Build
        run: |
          cmake --build --parallel --preset debug

      - name: Test
        run: |
          ctest --preset debug

